version: '3'

services:
  # node
  node:
    build:
      context: .
      dockerfile: ./.docker/node/Dockerfile
    container_name: node-app
    tty: true
    volumes:
      - .:/usr/src/app
    working_dir: "/usr/src/app" # working_dirはいらない？
    ports:
      - '9090:9090'

  # mysql
  mysql:
    container_name: mysql
    build:
      context: .
      dockerfile: ./.docker/mysql/Dockerfile
    hostname: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: test_database
      MYSQL_USER: user
      MYSQL_PASSWORD: rootroot
      TZ: ‘Asia/Tokyo’
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --skip-character-set-client-handshake
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql
      - ./.docker/mysql/my.cnf:/etc/mysql/my.conf # cnfで大丈夫みたいです

  # phpMyAdmin
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=mysql
      - PMA_USER=root
      - PMA_PASSWORD=rootroot
    ports:
      - 8080:80