name: test

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }} # runs a test on Ubuntu, Windows and macOS

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14.16.1]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker Build
        run: docker-compose up -d --build
      
      - name: Setup node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}
      
      - name: Install Dependecies
        run: yarn install
      
      - name: Docker up
        run: docker-compose up -d
        run: docker-compose ps
      
      - name: Run Tests
        run: yarn test
